
			<span class="titulo"> Registrar Jovén </span>
			<span class="subtitulo"> Datos Personales </span>
			<?php View::content(); ?>
			<?php echo Form::open('registro/registrar/'); echo Form::hidden('tipo', NULL, '2'); ?>
				<!-- Izquierdo -->
				<section class="grid_4 alpha">
						<label class="izq">Primer Nombre*</label>
						<?php echo Form::text('datos.primer_nombre', 'class="campotxt medium"', $primer_nombre); ?>
						<br/>
						<label class="izq">Primer Apellido</label>
						<?php echo Form::text('datos.primer_apellido', 'class="campotxt medium"', $primer_apellido); ?>
						<br/>
						<label class="izq">Cédula</label>
						<?php echo Registro::number('datos.cedula', 'class="campotxt small"', $cedula); ?>
						<br/>
						<label class="izq">Nacionalidad</label>
						<?php echo Registro::cmbNacionalidad('datos.nacionalidad', 'class="campotxt medium"', $nacionalidad); ?>
						<br/>
						<label class="izq">Estado Civil</label>
						<?php echo Registro::cmbCivil('adulto.estado_civil', 'class="campotxt medium"', $estado_civil); ?>
						<br/>
						<label class="izq">Religión</label>
						<?php echo Registro::cmbReligion('datos.religion', 'class="campotxt medium"', $religion); ?>
						<br/>
						<label class="izq">Sexo</label>
						<?php echo Registro::cmbSexo('datos.sexo', 'class="campotxt small"', $sexo); ?>
						<br/>
						<label class="izq">Telefóno</label>
						<?php echo Registro::tel('datos.telefono', 'class="campotxt small"', $telefono); ?>
						<label class="izq">Celular</label>
						<?php echo Registro::cel('datos.celular', 'class="campotxt small"', $celular); ?>
						<br/>
				</section>
				<!-- Izquierdo -->

				<!-- Derecho -->
				<section class="grid_4 omega">
						<label class="izq">Segundo Nombre</label>
						<?php echo Form::text('datos.segundo_nombre', 'class="campotxt medium"', $segundo_nombre); ?>
						<br/>
						<label class="izq">Segundo Apellido</label>
						<?php echo Form::text('datos.segundo_apellido', 'class="campotxt medium"', $segundo_apellido); ?>
						<br/>
						<label class="izq">Fecha de Nacimiento</label>
						<?php echo Registro::fecha('datos.fecha_nacimiento', 'class="campotxt small"', $fecha_nacimiento); ?>
						<br/>
						<label class="izq">Tipo de Sangre</label>
						<?php echo Registro::cmbSangre('datos.tipo_sangre', 'class="campotxt medium"', $tipo_sangre); ?>
						<br/>
						<label class="izq">Ocupación</label>
						<?php echo Registro::cmbOcupacion('datos.ocupacion', 'class="campotxt medium"', $ocupacion); ?>
						<br/>
						<label class="izq">Grado de Instrucción</label>
						<?php echo Registro::cmbInstruccion('datos.grado_instruccion', 'class="campotxt medium"', $grado_instruccion); ?>
						<br/>
						<label class="izq">Lugar de Nacimiento</label>
						<?php echo Form::text('datos.lugar_nacimiento', 'class="campotxt medium"', $lugar_nacimiento); ?>
						<br/>
						<label class="izq">Dirección</label>
						<?php echo Form::textarea('datos.direccion', ' class="campotxt medium"'); ?>
				</section>
				<!-- Derecho -->
				<div class="clear"></div>

				<!-- Completo -->
				<section class="grid_8 alpha omega">
					<div id="tabs">
						<ul>
							<li><a href="#tab-1">Datos Adultos</a></li>
							<li><a href="#tab-2">Datos Scouts</a></li>
						</ul>
						<div id="tab-1">
							<div class="grid_especial omega">
								<div class="grid_280">
									<label class="izq">Correo </label>
									<?php echo Registro::email('datos.email', 'class="campotxt medium"'); ?>
									<br/>
									<label class="izq">Lugar de Trabajo</label>
									<?php echo Form::text('adulto.lugar_trabajo', 'class="campotxt medium"'); ?>
									<br/>
									<label class="izq">Telf. de Trabajo</label>
									<?php echo Registro::tel('adulto.telefono_trabajo', 'class="campotxt medium"'); ?>
									<br/>

								</div>
								<div class="grid_280">
									<label class="izq">Fax de Trabajo</label>
									<?php echo Registro::tel('adulto.fax_trabajo', 'class="campotxt medium"'); ?>
									<br/>
									<label class="izq">Dirección <br/>de Trabajo</label>
									<?php echo Form::textarea('adulto.direccion_trabajo', ' class="campotxt medium"'); ?>
								</div>
							</div>
							<div class="clear"></div>
						</div>
						<div id="tab-2">
							<div class="grid_especial omega">
								<div class="grid_280">
									<label class="izq">Región</label>
									<?php echo Form::text('region', 'class="campotxt medium" readonly', 'Falcón'); ?>
									<br/>
									<label class="izq">Distrito</label>
									<?php echo Form::dbSelect('distrito', 'nombre', array('distrito', 'getDistritos', '1'), 'Seleccione', 'class="campotxt medium"'); ?>
									<br/>
									<label class="izq">Grupo</label>
									<?php echo Form::select('grupo', array('--'), 'class="campotxt medium"'); ?>
									<br/>
						          	<table>
						                <thead>
						                    <tr>
						                        <th>Fecha</th>
						                        <th>Cursos</th>
						                    </tr>
						                </thead>
						                <tbody>
						                    <tr>
						                        <td class="celda_corta">00/00/0000</td>
						                        <td>&nbsp;<a href="/adaba//adaba/default/public/index.php"  ><img src="/sgs/img/empty.png" class="add" border="0"></a></td>
						                    </tr>
						                </tbody>
						            </table>

								</div>
								<div class="grid_280">
									<label class="izq">Fecha de Ingreso</label>
									<?php echo Registro::fecha('fecha_promesa', 'class="campotxt small"') ?>
									<br/>
									<label class="izq">Cargo a Ocupar</label>
									<?php echo Form::select('cargo', array('--'), 'class="campotxt medium"'); ?>
									<br/>
									<?php echo Form::text('fuck', 'class="campotxt medium" style="visible:none;"'); ?>
									<br/>
						          	<table>
						                <thead>
						                    <tr>
						                        <th>Fecha</th>
						                        <th>Condecoraciones</th>
						                    </tr>
						                </thead>
						                <tbody>
						                    <tr>
						                        <td class="celda_corta">00/00/0000</td>
						                        <td>&nbsp;<a href="/adaba//adaba/default/public/index.php"  ><img src="/sgs/img/empty.png" class="add" border="0"></a></td>
						                    </tr>
						                </tbody>
						            </table>

								</div>
							</div>
							<div class="clear"></div>
						</div>
					</div>
					<div class="grid_1 prefix_7 alpha omega">
						<?php echo Form::submit('Registrar', 'class="botonessimples" id="aceptar"'); ?>
					</div>
				</section>
				<?php echo Form::close(); ?>
				<?php View::partial('formjs'); ?>
				<script type="text/javascript">
					$(document).ready(function() {
						$('#tabs').tabs();
						$('#distrito').on('change', function() {
							loadSelect( $('#grupo') );
							clearSelect( $('#cargo') );
							$.getJSON(
								'<?php echo PUBLIC_PATH; ?>registro/getGrupos/' + $( this ).val(),
								function(data) {
									clearSelect( $('#grupo') );
									if ( data.status == 'OK' ) {
										$.each(data.grupos, function(i, grupo) {
											$('#grupo').append( new Option(grupo.nombre, grupo.id) );
										});
									}
								}
							);
						});

						$('#grupo').on('change', function() {
							loadSelect( $('#cargo') );
							// clearSelect( $('#cargo') );
							$.getJSON(
								'<?php echo PUBLIC_PATH; ?>registro/getCargos/1-' + $('#distrito').val() + '-' + $( this ).val(),
								function(data) {
									clearSelect( $('#cargo') );
									if ( data.status == 'OK' ) {
										$.each(data.cargos, function(i, item) {
											var cargo = item.nombre.replace(' No Aplica','');
											$('#cargo').append( new Option(cargo.replace(' Unidad',''), item.id) );
										});
									}
								}
							);
						});

						function clearSelect(objecto) {
							objecto.empty();
							objecto.append( new Option('--', 0) );
						}
						function loadSelect(objecto) {
							objecto.empty();
							objecto.append( new Option("Cargando...", "0") );
						}
					});
				</script>