
			<span class="titulo"> Registrar Jovén </span>
			<span class="subtitulo"> Datos Personales </span>
			<?php echo Form::open('registro/registrar/'); ?>
				<!-- Izquierdo -->
				<section class="grid_4 alpha">
						<label class="izq">Primer Nombre</label>
						<?php echo Form::text('datos.primer_nombre', 'class="campotxt medium"'); ?>
						<br/>
						<label class="izq">Primer Apellido</label>
						<?php echo Form::text('datos.primer_apellido', 'class="campotxt medium"'); ?>
						<br/>
						<label class="izq">Cédula</label>
						<?php echo Registro::number('datos.cedula', 'class="campotxt medium"'); ?>
						<br/>
						<label class="izq">Nacionalidad</label>
						<?php echo Registro::cmbNacionalidad('datos.nacionalidad', 'class="campotxt medium"'); ?>
						<br/>
						<label class="izq">Grado de Instrucción</label>
						<?php echo Registro::cmbInstruccion('datos.grado_instruccion', 'class="campotxt medium"'); ?>
						<br/>
						<label class="izq">Religión</label>
						<?php echo Registro::cmbReligion('datos.religion', 'class="campotxt medium"'); ?>
						<br/>
						<label class="izq">Sexo</label>
						<?php echo Registro::cmbSexo('datos.sexo', 'class="campotxt small"'); ?>
						<br/>
						<label class="izq">Telefóno</label>
						<?php echo Registro::tel('datos.telefono', 'class="campotxt medium"'); ?>
						<label class="izq">Lugar de Estudio <br/>o Trabajo</label>
						<br/>
						<?php echo Form::text('scouts.lugar_estudio_trabajo', 'class="campotxt medium"'); ?>
				</section>
				<!-- Izquierdo -->

				<!-- Derecho -->
				<section class="grid_4 omega">
						<label class="izq">Segundo Nombre</label>
						<?php echo Form::text('datos.segundo_nombre', 'class="campotxt medium"') ?>
						<br/>
						<label class="izq">Segundo Apellido</label>
						<?php echo Form::text('datos.segundo_apellido', 'class="campotxt medium"') ?>
						<br/>
						<label class="izq">Fecha de Nacimiento</label>
						<?php echo Registro::fecha('datos.fecha_nacimiento', 'class="campotxt small"'); ?>
						<br/>
						<label class="izq">Tipo de Sangre</label>
						<?php echo Registro::cmbSangre('datos.tipo_sangre', 'class="campotxt medium"'); ?>
						<br/>
						<label class="izq">Ocupación</label>
						<?php echo Registro::cmbOcupacion('datos.ocupacion', 'class="campotxt medium"'); ?>
						<br/>
						<label class="izq">Estudios</label>
						<?php echo Registro::cmbEstudios('scouts.tipo_estudio', 'class="campotxt small"'); ?>
						<br/>
						<label class="izq">Lugar de Nacimiento</label>
						<?php echo Form::text('datos.lugar_nacimiento', 'class="campotxt medium"') ?>
						<br/>
						<label class="izq">Celular</label>
						<?php echo Registro::cel('datos.celular', 'class="campotxt medium"') ?>
						<br/>
						<label class="izq">Correo electrónico</label>
						<?php echo Registro::email('datos.email', 'class="campotxt medium"') ?>
						<br/>
				</section>
				<!-- Derecho -->
				<div class="clear"></div>
				<section class="grid_8 alpha omega">
					<div class="grid_2 alpha">
						<label class="izq">Dirección</label>
					</div>
					<div class="grid_6 omega">
						<?php echo Form::textarea('datos.direccion', ' class="campotxt extralarge" style="width:100%;"'); ?>
						
					</div>
				</section>

				<!-- Completo -->
				<section class="grid_8 alpha omega">
					<div id="tabs">
						<ul>
							<li><a href="#tab-1">Datos del Representante</a></li>
							<li><a href="#tab-2">Datos Scouts</a></li>
						</ul>
						<div id="tab-1">
							<div class="grid_7 omega">
								<div class="grid_2">
									<label class="izq">Nombre Completo</label>
									<br/>
									<label class="izq">Nacionalidad</label>
									<br/>
									<label class="izq">Cédula</label>
									<br/>
									<label class="izq">Tipo de Sangre</label>
									<br/>
									<label class="izq">Religión</label>
									<br/>
									<label class="izq">Grado de Instrucción</label>
									<br/>
									<label class="izq">Ocupación</label>
									<br/>
									<label class="izq">Telefóno</label>
									<br/>
									<label class="izq">Celular</label>
									<br/>
									<label class="izq">Correo Electrónico</label>
									<br/>
									<label class="izq">Fax</label>
									<br/>
									<label class="izq">Dirección</label>
									<br/>
								</div>
								<div class="grid_2">
									<?php echo Form::text('rep1.nombre', 'class="campotxt medium"') ?>
									<br/>
									<?php echo Registro::cmbNacionalidad('rep1.nacionalidad', 'class="campotxt medium"') ?>
									<br/>
									<?php echo Registro::number('rep1.cedula', 'class="campotxt medium"') ?>
									<br/>
									<?php echo Registro::cmbSangre('rep1.sangre', 'class="campotxt medium"') ?>
									<br/>
									<?php echo Registro::cmbReligion('rep1.religion', 'class="campotxt medium"') ?>
									<br/>
									<?php echo Registro::cmbInstruccion('rep1.grado_instruccion', 'class="campotxt medium"') ?>
									<br/>
									<?php echo Registro::cmbOcupacion('rep1.ocupacion', 'class="campotxt medium"') ?>
									<br/>
									<?php echo Registro::tel('rep1.telefono', 'class="campotxt medium"') ?>
									<br/>
									<?php echo Registro::cel('rep1.celular', 'class="campotxt medium"') ?>
									<br/>
									<?php echo Registro::email('rep1.email', 'class="campotxt medium"') ?>
									<br/>
									<?php echo Registro::tel('rep1.fax', 'class="campotxt medium"') ?>
									<br/>
									<?php echo Form::textarea('rep1.direccion', 'class="campotxt medium"') ?>
									<br/>
								</div>
								<div class="grid_2">
									<?php echo Form::text('rep2.nombre', 'class="campotxt medium"') ?>
									<br/>
									<?php echo Registro::cmbNacionalidad('rep2.nacionalidad', 'class="campotxt medium"') ?>
									<br/>
									<?php echo Registro::number('rep2.cedula', 'class="campotxt medium"') ?>
									<br/>
									<?php echo Registro::cmbSangre('rep2.sangre', 'class="campotxt medium"') ?>
									<br/>
									<?php echo Registro::cmbReligion('rep2.religion', 'class="campotxt medium"') ?>
									<br/>
									<?php echo Registro::cmbInstruccion('rep2.grado_instruccion', 'class="campotxt medium"') ?>
									<br/>
									<?php echo Registro::cmbOcupacion('rep2.ocupacion', 'class="campotxt medium"') ?>
									<br/>
									<?php echo Registro::tel('rep2.telefono', 'class="campotxt medium"') ?>
									<br/>
									<?php echo Registro::cel('rep2.celular', 'class="campotxt medium"') ?>
									<br/>
									<?php echo Registro::email('rep2.email', 'class="campotxt medium"') ?>
									<br/>
									<?php echo Registro::tel('rep2.fax', 'class="campotxt medium"') ?>
									<br/>
									<?php echo Form::textarea('rep2.direccion', 'class="campotxt medium"') ?>
									<br/>
								</div>
							</div>
							<div class="clear"></div>
						</div>
						<div id="tab-2">
							<div class="grid_especial omega">
								<div class="grid_280">
									<label class="izq">Distrito</label>
									<?php echo Form::hidden('scouts.pais_id', '1');
									echo Form::dbSelect('scouts.distrito_id', 'nombre', array('distrito', 'getDistritos', '1'), 'Seleccione', 'class="campotxt medium"'); ?>
									<br/>
									<label class="izq">Unidad</label>
									<?php echo Form::select('scouts.grupo_ramas_id', array('--'), 'class="campotxt medium"'); ?>
									<br/>
									<label class="izq">Fecha de Ingreso</label>
									<?php echo Registro::fecha('scouts.fecha_ingreso', 'class="campotxt small"'); ?>
									<br/>
						          	<table>
						                <thead>
						                    <tr>
						                        <th>Fecha</th>
						                        <th>Adelanto B&aacute;sico</th>
						                    </tr>
						                </thead>
						                <tbody>
						                    <tr>
						                        <td class="celda_corta">00/00/0000</td>
						                        <td>&nbsp;<a href="#"><img src="/sgs/img/empty.png" class="add" border="0"></a></td>
						                    </tr>
						                </tbody>
						            </table>
						          	<table>
						                <thead>
						                    <tr>
						                        <th>Fecha</th>
						                        <th>Cursos y Talleres</th>
						                    </tr>
						                </thead>
						                <tbody>
						                    <tr>
						                        <td class="celda_corta">00/00/0000</td>
						                        <td>&nbsp;<a href="#"><img src="/sgs/img/empty.png" class="add" border="0"></a></td>
						                    </tr>
						                </tbody>
						            </table>
						            <table>
						                <thead>
						                    <tr>
						                        <th>Fecha</th>
						                        <th>CVAL</th>
						                    </tr>
						                </thead>
						                <tbody>
						                    <tr>
						                        <td class="celda_corta">00/00/0000</td>
						                        <td>&nbsp;<a href="#"><img src="/sgs/img/empty.png" class="add" border="0"></a></td>
						                    </tr>
						                </tbody>
						            </table>
								</div>
								<div class="grid_280">
									<label class="izq">Grupo</label>
									<?php echo Form::select('scouts.grupo_id', array('--'), 'class="campotxt medium"'); ?>
									<br/>
									<label class="izq">Pequeña Grupo</label>
									<?php echo Form::select('scouts.grupo_ramas_agrupaciones_id', array('--'), 'class="campotxt medium"'); ?>
									<br/>
									<label class="izq">Fecha de Promesa</label>
									<?php echo Registro::fecha('scouts.fecha_promesa', 'class="campotxt small"'); ?>
									<br/>
						          	<table>
						                <thead>
						                    <tr>
						                        <th>Fecha</th>
						                        <th>Especialidades</th>
						                    </tr>
						                </thead>
						                <tbody>
						                    <tr>
						                        <td class="celda_corta">00/00/0000</td>
						                        <td>&nbsp;<a href="#"><img src="/sgs/img/empty.png" class="add" border="0"></a></td>
						                    </tr>
						                </tbody>
						            </table>
						          	<table>
						                <thead>
						                    <tr>
						                        <th>Fecha</th>
						                        <th>CAC</th>
						                    </tr>
						                </thead>
						                <tbody>
						                    <tr>
						                        <td class="celda_corta">00/00/0000</td>
						                        <td>&nbsp;<a href="#"><img src="/sgs/img/empty.png" class="add" border="0"></a></td>
						                    </tr>
						                </tbody>
						            </table>
						            <table>
						                <thead>
						                    <tr>
						                        <th>Fecha</th>
						                        <th>Condecoraciones</th>
						                    </tr>
						                </thead>
						                <tbody>
						                    <tr>
						                        <td class="celda_corta">00/00/0000</td>
						                        <td>&nbsp;<a href="#"><img src="/sgs/img/empty.png" class="add" border="0"></a></td>
						                    </tr>
						                </tbody>
						            </table>
								</div>
							</div>
							<div class="clear"></div>
						</div>
					</div>
					<div class="grid_1 prefix_7 alpha omega">
						<?php echo Form::submit('Registrar', 'class="botonessimples" id="aceptar"'); ?>
					</div>
				</section>
			<?php echo Form::close(); ?>
			<?php View::partial('formjs'); ?>
				<script type="text/javascript">
					$(document).ready(function() {
						$('#tabs').tabs();
						$('#scouts_distrito_id').on('change', function() {
							var objecto = $('#scouts_grupo_id');
							objecto.append( new Option("Cargando...", "0") );
							clearSelect( $('#scouts_grupo_id') );
							clearSelect( $('#scouts_grupo_ramas_id') );
							clearSelect( $('#scouts_grupo_ramas_agrupaciones_id') );
							$.getJSON(
								'<?php echo PUBLIC_PATH; ?>registro/getGrupos/' + $( this ).val(),
								function(data) {
									// clearSelect(objecto);
									if ( data.status == 'OK' ) {
										$.each(data.grupos, function(i, grupo) {
											objecto.append( new Option(grupo.nombre, grupo.id) );
										});
									}
								}
							);
						});
						$('#scouts_grupo_id').on('change', function() {
							var objecto = $('#scouts_grupo_ramas_id');
							objecto.append( new Option("Cargando...", "0") );
							clearSelect( $('#scouts_grupo_ramas_id') );
							clearSelect( $('#scouts_grupo_ramas_agrupaciones_id') );
							$.getJSON(
								'<?php echo PUBLIC_PATH; ?>registro/getRamas/' + $( this ).val(),
								function(data) {
									clearSelect(objecto);
									if ( data.status == 'OK' ) {
										$.each(data.ramas, function(i, grupo) {
											objecto.append( new Option(grupo.nombre, grupo.id) );
										});
									}
								}
							);
						});
						$('#scouts_grupo_ramas_id').on('change', function() {
							var objecto = $('#scouts_grupo_ramas_agrupaciones_id');
							objecto.append( new Option("Cargando...", "0") );
							clearSelect( objecto );
							$.getJSON(
								'<?php echo PUBLIC_PATH; ?>registro/getAgrupaciones/' + $( this ).val(),
								function(data) {
									clearSelect(objecto);
									if ( data.status == 'OK' ) {
										$.each(data.agrupaciones, function(i, grupo) {
											objecto.append( new Option(grupo.nombre, grupo.id) );
										});
									}
								}
							);
						});
					});
					function clearSelect(objecto) {
						objecto.empty();
						objecto.append( new Option('--', 0) );
					}
				</script>