
		<header id="head">
			<div class="container_16">
					<div class="grid_9 suffix_7">
						<h1>Sistema de Gestion Scout Adaba</h1>V0.1
					</div>

					<div class="grid_1 prefix_11">
						<?php echo Html::link('bienvenida/', 'Inicio'); ?>
					</div>
					<div class="grid_1">
						<?php echo Html::link('me/', 'Perfil'); ?>
					</div>
					<div class="grid_2">
						<?php echo Html::link('me/clave/', 'Cambiar Clave'); ?>
					</div>
					<div class="grid_1">
						<?php echo Html::link('logout/', 'Salir'); ?>
					</div>

			</div>
		</header>
