<?php View::content(); ?>
    <?php echo Html::img('logo.gif', 'Sistema de Gesti&oacute;n Scout Adaba', 'id="logo_bienvenida"') ?>
    <h3>&iquest;Porque el nombre de Adaba?</h3>
    <p>Adaba o Adabacoa, significa bosque en el dialecto Caquetio, eso es nuestro sistema un "bosque", ese bosque en donde cohabitaremos de una forma más respetuosa para nuestro medio ambiente disminuyendo nuestro consumo de papel en el cumplimiento de nuestra labor dentro del movimiento y además de disminuir nuestra huella de carbón.</p>
    <h3>&iquest;Que es Adaba?</h3>
    <p>Es un sistema de integral que crecerá y se adecuará a las necesidades de nuestro movimiento, cual bosque. Desarrollado con tecnologías y estandares libres con la finalidad de facilitar a los adultos Scout y líderes de los pequeños grupos su labor, con una herramienta más interactivo y amigable.</p>
    <h3>&iquest;Cual es  el objetivo de Abada?</h3>
    <p>Dotar a cada Scout de las herramientas necesarias para facilitar su labor dentro del movimiento y entregar una cuota de responsabilidad a nuestros Jóvenes. Además la reducción considerable en el uso de papel.</p>